spring.datasource.url=jdbc:sqlite:foodie.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate ddl-auto (update, create, create-drop, validate, none)
spring.jpa.hibernate.ddl-auto=create

# Dialect for SQLite (Hibernate 6+ has it built-in)
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Show SQL queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8081
